backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/src/site/media/"
public_folder: "/media/"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/site/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ['page'], default: 'page'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Teaser Title", name: "teaserTitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}